number: '0123456789'                                                # can be emptied
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"                      # can be emptied
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'   # can be emptied
experiment_name: 'en_custom_5'          # set 1
train_data: 'all_data/en_custom'        # set 2
valid_data: 'all_data/en_custom'        # set 3
manualSeed: 1111
workers: 6                              #6
batch_size: 128                         #32
num_iter: 2000                          #300000
valInterval: 200                        #200000
saved_model: 'saved_models/en_custom_5/best_accuracy.pth' # 'saved_models/en_filtered/iter_300000.pth' , set 4
FT: False
optim: False                            # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
# Data processing
select_data: 'en_custom'                # this is dataset folder in train_data, set 5
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 130 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False